---
interfaces:
  - name: "GigabitEthernet1"
    enabled: True
    type: "ethernetCsmacd"
    ipv6_address: #update for your local network
    ipv6_address_cli: #update for your local network
    prefix_length: 64
    description: "Uplink1"

  - name: "GigabitEthernet2"
    enabled: True
    type: "ethernetCsmacd"
    ipv6_address: "2001:db8:172::1"
    ipv6_address_cli: "2001:db8:172::1/64"
    prefix_length: 64
    description: "Connection to edge network"

eigrp_v6:
  as: 6
  interfaces:
    - name: "GigabitEthernet1"
    - name: "GigabitEthernet2"
  router_id: "1.1.1.1"

default_route:
  name: "default"
  identifier:
    - type: "STATIC"
      name: "static"
  destination: "::/0"
  next_hop: "GigabitEthernet1 fe80::68d7:9aff:fe3b:486e"

nat66:
 inside_interface: "GigabitEthernet2"
 outside_interface: "GigabitEthernet1"
 prefix:
   inside: "2001:db8:10::/64"
   outside: #update for your local network
