---
# tasks file for DHCPv6
- name: Render OpenConfig IPv6 template
  template:
    src: "templates/iosxe_native_yang_dhcpv6.j2"
    dest: "/tmp/iosxe_native_yang_dhcpv6_{{ inventory_hostname }}.xml"

- name: Apply configuration to IOS XE router
  ansible.netcommon.netconf_config:
    target: running
    content: "{{ lookup('file', '/tmp/iosxe_native_yang_dhcpv6_{{ inventory_hostname }}.xml') }}"
    commit: true
    
- name: Delete temporary IPv6 interface config file
  ansible.builtin.file:
    path: /tmp//tmp/iosxe_native_yang_dhcpv6_{{ inventory_hostname }}.xml
    state: absent
  delegate_to: localhost

- name: Render IPv6 DHCPv6 interface template
  template:
    src: "templates/iosxe_native_yang_dhcpv6.j2"
    dest: "/tmp/iosxe_native_yang_dhcpv6_interface{{ inventory_hostname }}.xml"

- name: Apply configuration to IOS XE router
  ansible.netcommon.netconf_config:
    target: running
    content: "{{ lookup('file', '/tmp/iosxe_native_yang_dhcpv6_interface{{ inventory_hostname }}.xml') }}"
    commit: true
    
- name: Delete temporary IPv6 interface config file
  ansible.builtin.file:
    path: /tmp//tmp/iosxe_native_yang_dhcpv6_interface{{ inventory_hostname }}.xml
    state: absent
  delegate_to: localhost  


####### USE THE BELOW IF YOU PREFER TO USE CLI COMMANDS OVER NETCONF############### 
#- name: Render DHCPv6 configuration for IOS-XE CLI
 # template:
  #  src: "templates/ios_xe_dhcpv6_cli.j2"
   # dest: "/tmp/ios_xe_dhcpv6_config_{{ inventory_hostname }}.txt"

#- name: Apply DHCPv6 configuration to IOS-XE router
 # cisco.ios.ios_command:
  #  commands:
   #   - "configure terminal"
    #  - "{{ lookup('file', '/tmp/ios_xe_dhcpv6_config_{{ inventory_hostname }}.txt') }}"
      
#- name: Delete temporary DHCPv6 config file
 # ansible.builtin.file:
  #  path: /tmp/ios_xe_dhcpv6_config_{{ inventory_hostname }}.txt
   # state: absent
  #delegate_to: localhost
